package model;
// Generated 07/06/2019 22:11:26 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int filmId;
     private Language language;
     private String title;
     private String description;
     private Serializable releaseYear;
     private short rentalDuration;
     private BigDecimal rentalRate;
     private Short length;
     private BigDecimal replacementCost;
     private String rating;
     private Date lastUpdate;
     private Serializable specialFeatures;
     private Set<Inventory> inventories = new HashSet<Inventory>(0);
     private Set<FilmCategory> filmCategories = new HashSet<FilmCategory>(0);
     private Set<FilmActor> filmActors = new HashSet<FilmActor>(0);

    public Film() {
    }

	
    public Film(int filmId, Language language, String title, short rentalDuration, BigDecimal rentalRate, BigDecimal replacementCost, Date lastUpdate) {
        this.filmId = filmId;
        this.language = language;
        this.title = title;
        this.rentalDuration = rentalDuration;
        this.rentalRate = rentalRate;
        this.replacementCost = replacementCost;
        this.lastUpdate = lastUpdate;
    }
    public Film(int filmId, Language language, String title, String description, Serializable releaseYear, short rentalDuration, BigDecimal rentalRate, Short length, BigDecimal replacementCost, String rating, Date lastUpdate, Serializable specialFeatures, Set<Inventory> inventories, Set<FilmCategory> filmCategories, Set<FilmActor> filmActors) {
       this.filmId = filmId;
       this.language = language;
       this.title = title;
       this.description = description;
       this.releaseYear = releaseYear;
       this.rentalDuration = rentalDuration;
       this.rentalRate = rentalRate;
       this.length = length;
       this.replacementCost = replacementCost;
       this.rating = rating;
       this.lastUpdate = lastUpdate;
       this.specialFeatures = specialFeatures;
       this.inventories = inventories;
       this.filmCategories = filmCategories;
       this.filmActors = filmActors;
    }
   
    public int getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(int filmId) {
        this.filmId = filmId;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Serializable getReleaseYear() {
        return this.releaseYear;
    }
    
    public void setReleaseYear(Serializable releaseYear) {
        this.releaseYear = releaseYear;
    }
    public short getRentalDuration() {
        return this.rentalDuration;
    }
    
    public void setRentalDuration(short rentalDuration) {
        this.rentalDuration = rentalDuration;
    }
    public BigDecimal getRentalRate() {
        return this.rentalRate;
    }
    
    public void setRentalRate(BigDecimal rentalRate) {
        this.rentalRate = rentalRate;
    }
    public Short getLength() {
        return this.length;
    }
    
    public void setLength(Short length) {
        this.length = length;
    }
    public BigDecimal getReplacementCost() {
        return this.replacementCost;
    }
    
    public void setReplacementCost(BigDecimal replacementCost) {
        this.replacementCost = replacementCost;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Serializable getSpecialFeatures() {
        return this.specialFeatures;
    }
    
    public void setSpecialFeatures(Serializable specialFeatures) {
        this.specialFeatures = specialFeatures;
    }
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }
    public Set<FilmCategory> getFilmCategories() {
        return this.filmCategories;
    }
    
    public void setFilmCategories(Set<FilmCategory> filmCategories) {
        this.filmCategories = filmCategories;
    }
    public Set<FilmActor> getFilmActors() {
        return this.filmActors;
    }
    
    public void setFilmActors(Set<FilmActor> filmActors) {
        this.filmActors = filmActors;
    }




}


