package model;
// Generated 07/06/2019 22:11:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private int staffId;
     private Address address;
     private String firstName;
     private String lastName;
     private String email;
     private short storeId;
     private boolean active;
     private String username;
     private String password;
     private Date lastUpdate;
     private byte[] picture;
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<Rental> rentals = new HashSet<Rental>(0);
     private Set<Store> stores = new HashSet<Store>(0);

    public Staff() {
    }

	
    public Staff(int staffId, Address address, String firstName, String lastName, short storeId, boolean active, String username, Date lastUpdate) {
        this.staffId = staffId;
        this.address = address;
        this.firstName = firstName;
        this.lastName = lastName;
        this.storeId = storeId;
        this.active = active;
        this.username = username;
        this.lastUpdate = lastUpdate;
    }
    public Staff(int staffId, Address address, String firstName, String lastName, String email, short storeId, boolean active, String username, String password, Date lastUpdate, byte[] picture, Set<Payment> payments, Set<Rental> rentals, Set<Store> stores) {
       this.staffId = staffId;
       this.address = address;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.storeId = storeId;
       this.active = active;
       this.username = username;
       this.password = password;
       this.lastUpdate = lastUpdate;
       this.picture = picture;
       this.payments = payments;
       this.rentals = rentals;
       this.stores = stores;
    }
   
    public int getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(int staffId) {
        this.staffId = staffId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public short getStoreId() {
        return this.storeId;
    }
    
    public void setStoreId(short storeId) {
        this.storeId = storeId;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }
    public Set<Rental> getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Set<Rental> rentals) {
        this.rentals = rentals;
    }
    public Set<Store> getStores() {
        return this.stores;
    }
    
    public void setStores(Set<Store> stores) {
        this.stores = stores;
    }




}


